# Cleaning Pandas DataFrames

In [1]:
from pathlib import Path
import pandas as pd

## DataFrame Inspection

In [2]:
data_folder = Path('../../data/')
old_path = Path(f'{data_folder}/nederland_pop_stats_old.csv')

In [3]:
pop_stats = pd.read_csv(old_path)
pop_stats.shape

(101, 22)

In [4]:
pop_stats.head(1)

,Sex,Regions,Periods,Population on 1 January (number),Population density (number),Live born children Live born children (number),"Live born children, ratio (per 1,000)",Deaths Deaths (number),"Deaths, ratio (per 1,000)",Natural increase (number),...,Due to immigration (number),Due to intermunicipal moves (number),Departures from municipality Total departures including administra... (number),"Total departures including adm..., ratio (per 1,000)",Due to emigration including administr... (number),Due to intermunicipal moves (number).1,Net migration including administrative.. (number),Population growth Population growth (number),"Population growth, ratio (per 1,000)",Population on 31 December (number)
0,Total male and female,The Netherlands,2024.0,"17,942,942",533,"166,143",9.2,"172,165",9.6,"-6,022",...,"316,305","802,898","1,011,435",56.2,"208,537","802,898","107,768","101,085",5.6,"18,044,027"

## Deleting Unwanted Columns

In [5]:
for i,v in enumerate(pop_stats.columns):
    print(i, v)

0 Sex
1 Regions
2 Periods
3 Population on 1 January (number)
4 Population density (number)
5 Live born children Live born children (number)
6 Live born children, ratio (per 1,000)
7 Deaths Deaths (number)
8 Deaths, ratio (per 1,000)
9 Natural increase (number)
10 Arrivals in municipality Total arrivals (number)
11 Total arrivals, ratio (per 1,000)
12 Due to immigration (number)
13 Due to intermunicipal moves (number)
14 Departures from municipality Total departures including administra... (number)
15 Total departures including adm..., ratio (per 1,000)
16 Due to emigration including administr... (number)
17 Due to intermunicipal moves (number).1
18 Net migration including administrative.. (number)
19 Population growth Population growth (number)
20 Population growth, ratio (per 1,000)
21 Population on 31 December (number)

In [6]:
pop_stats = pop_stats.drop(columns=pop_stats.columns[[0, 2, 9, 12, 13, 16, 17, 21]])

for i,v in enumerate(pop_stats.columns):
    print(i, v)

0 Regions
1 Population on 1 January (number)
2 Population density (number)
3 Live born children Live born children (number)
4 Live born children, ratio (per 1,000)
5 Deaths Deaths (number)
6 Deaths, ratio (per 1,000)
7 Arrivals in municipality Total arrivals (number)
8 Total arrivals, ratio (per 1,000)
9 Departures from municipality Total departures including administra... (number)
10 Total departures including adm..., ratio (per 1,000)
11 Net migration including administrative.. (number)
12 Population growth Population growth (number)
13 Population growth, ratio (per 1,000)

In [7]:
pop_stats.head(1)

,Regions,Population on 1 January (number),Population density (number),Live born children Live born children (number),"Live born children, ratio (per 1,000)",Deaths Deaths (number),"Deaths, ratio (per 1,000)",Arrivals in municipality Total arrivals (number),"Total arrivals, ratio (per 1,000)",Departures from municipality Total departures including administra... (number),"Total departures including adm..., ratio (per 1,000)",Net migration including administrative.. (number),Population growth Population growth (number),"Population growth, ratio (per 1,000)"
0,The Netherlands,"17,942,942",533,"166,143",9.2,"172,165",9.6,"1,119,203",62.2,"1,011,435",56.2,"107,768","101,085",5.6

## Renaming Columns

In [8]:
new_columns = {pop_stats.columns[i]: new_name for i, new_name in enumerate([
    'region',
    'total_population',
    'population_density',
    'total_births',
    'birth_ratio',
    'total_deaths',
    'death_ratio',
    'total_arrivals',
    'arrival_ratio',
    'total_departures',
    'departure_ratio',
    'net_migration',
    'total_population_growth',
    'population_growth_ratio'
])}

pop_stats = pop_stats.rename(columns=new_columns)
pop_stats.reset_index()
pop_stats.head(1)

,region,total_population,population_density,total_births,birth_ratio,total_deaths,death_ratio,total_arrivals,arrival_ratio,total_departures,departure_ratio,net_migration,total_population_growth,population_growth_ratio
0,The Netherlands,"17,942,942",533,"166,143",9.2,"172,165",9.6,"1,119,203",62.2,"1,011,435",56.2,"107,768","101,085",5.6

## Replacing NaN Values

In [9]:
pop_stats.isna().sum()

region                      1
total_population           28
population_density         28
total_births               28
birth_ratio                28
total_deaths               28
death_ratio                28
total_arrivals             28
arrival_ratio              28
total_departures           28
departure_ratio            28
net_migration              28
total_population_growth    28
population_growth_ratio    28
dtype: int64

In [10]:
pop_stats = pop_stats.fillna(0)
pop_stats.isna().sum()

region                     0
total_population           0
population_density         0
total_births               0
birth_ratio                0
total_deaths               0
death_ratio                0
total_arrivals             0
arrival_ratio              0
total_departures           0
departure_ratio            0
net_migration              0
total_population_growth    0
population_growth_ratio    0
dtype: int64

In [11]:
pop_stats.head(1)

,region,total_population,population_density,total_births,birth_ratio,total_deaths,death_ratio,total_arrivals,arrival_ratio,total_departures,departure_ratio,net_migration,total_population_growth,population_growth_ratio
0,The Netherlands,"17,942,942",533,"166,143",9.2,"172,165",9.6,"1,119,203",62.2,"1,011,435",56.2,"107,768","101,085",5.6

## Removing Commas from Numeric Columns

In [12]:
pop_stats.apply(lambda col: col.astype(str).str.contains(','), axis=1).sum()

region                      1
total_population           73
population_density         21
total_births               60
birth_ratio                 0
total_deaths               60
death_ratio                 0
total_arrivals             69
arrival_ratio               0
total_departures           69
departure_ratio             0
net_migration              57
total_population_growth    48
population_growth_ratio     0
dtype: int64

In [13]:
pop_stats = pop_stats.replace({',': ''}, regex=True)

In [14]:
pop_stats.head(1)

,region,total_population,population_density,total_births,birth_ratio,total_deaths,death_ratio,total_arrivals,arrival_ratio,total_departures,departure_ratio,net_migration,total_population_growth,population_growth_ratio
0,The Netherlands,17942942,533,166143,9.2,172165,9.6,1119203,62.2,1011435,56.2,107768,101085,5.6

## Typecasting Columns

In [15]:
pop_stats.dtypes

region                      object
total_population            object
population_density          object
total_births                object
birth_ratio                float64
total_deaths                object
death_ratio                float64
total_arrivals              object
arrival_ratio              float64
total_departures            object
departure_ratio            float64
net_migration               object
total_population_growth     object
population_growth_ratio    float64
dtype: object

In [16]:
for column in pop_stats.columns[1:]:
    pop_stats[column] = pd.to_numeric(pop_stats[column])

pop_stats.dtypes

region                      object
total_population             int64
population_density           int64
total_births                 int64
birth_ratio                float64
total_deaths                 int64
death_ratio                float64
total_arrivals               int64
arrival_ratio              float64
total_departures             int64
departure_ratio            float64
net_migration                int64
total_population_growth      int64
population_growth_ratio    float64
dtype: object

In [17]:
pop_stats['population_density'] = pop_stats['population_density'].astype('float64')
pop_stats['population_density'].dtypes

dtype('float64')

## Removing Non-Provinces

In [18]:
for i in pop_stats['region']:
    print(i)

The Netherlands
Noord-Nederland (LD)
Oost-Nederland (LD)
West-Nederland (LD)
Zuid-Nederland (LD)
Groningen (PV)
Fryslân (PV)
Drenthe (PV)
Overijssel (PV)
Flevoland (PV)
Gelderland (PV)
Utrecht (PV)
Noord-Holland (PV)
Zuid-Holland (PV)
Zeeland (PV)
Noord-Brabant (PV)
Limburg (PV)
Oost-Groningen (CR)
Delfzijl en omgeving (CR)
Overig Groningen (CR)
Noord-Friesland (CR)
Zuidwest-Friesland (CR)
Zuidoost-Friesland (CR)
Noord-Drenthe (CR)
Zuidoost-Drenthe (CR)
Zuidwest-Drenthe (CR)
Noord-Overijssel (CR)
Zuidwest-Overijssel (CR)
Twente (CR)
Veluwe (CR)
Achterhoek (CR)
Arnhem/Nijmegen (CR)
Zuidwest-Gelderland (CR)
Utrecht (CR)
Kop van Noord-Holland (CR)
Alkmaar en omgeving (CR)
IJmond (CR)
Agglomeratie Haarlem (CR)
Zaanstreek (CR)
Groot-Amsterdam (CR)
Het Gooi en Vechtstreek (CR)
Agglomeratie Leiden en Bollenstreek (CR)
Agglomeratie 's-Gravenhage (CR)
Delft en Westland (CR)
Oost-Zuid-Holland (CR)
Groot-Rijnmond (CR)
Zuidoost-Zuid-Holland (CR)
Zeeuwsch-Vlaanderen (CR)
Overig Zeeland (CR)
West-Noord-Brabant (CR)
Midden-Noord-Brabant (CR)
Noordoost-Noord-Brabant (CR)
Zuidoost-Noord-Brabant (CR)
Noord-Limburg (CR)
Midden-Limburg (CR)
Zuid-Limburg (CR)
Flevoland (CR)
Aa en Hunze
Aagtekerke
Aalburg
Aalsmeer
Aalten
Ter Aar
Aardenburg
Aarle-Rixtel
Abbekerk
Abbenbroek
Abcoude
Achtkarspelen
Achttienhoven (U.)
Adorp
Aduard
Akersloot
Alblasserdam
Albrandswaard
Alem Maren en Kessel
Alkemade
Alkmaar
Almelo
Almere
Almkerk
Alphen aan den Rijn
Alphen en Riel
Alphen-Chaam
Altena
Ambt Delden
Ambt Montfort
Ambt-Vollenhove
Amby
Ameide
Ameland
Amerongen
Amersfoort
Ammerstol
Ammerzoden
Amstelveen
Amstenrade
Amsterdam
Andel
Andijk
0

In [19]:
pop_stats = pop_stats[pop_stats['region'].astype('str').str.contains('(PV)', regex=False)]
pop_stats = pop_stats.reset_index()

pop_stats

,index,region,total_population,population_density,total_births,birth_ratio,total_deaths,death_ratio,total_arrivals,arrival_ratio,total_departures,departure_ratio,net_migration,total_population_growth,population_growth_ratio
0,5,Groningen (PV),601347,260.0,4816,8.0,6294,10.5,58540,97.2,55699,92.5,2841,1486,2.5
1,6,Fryslân (PV),661904,198.0,5684,8.6,7146,10.8,33334,50.3,29516,44.5,3818,2318,3.5
2,7,Drenthe (PV),504129,191.0,4037,8.0,6045,12.0,26872,53.2,22388,44.3,4484,2400,4.8
3,8,Overijssel (PV),1189033,359.0,11158,9.4,11781,9.9,56060,47.0,48614,40.8,7446,6756,5.7
4,9,Flevoland (PV),450826,320.0,4890,10.8,3033,6.7,28001,61.7,24275,53.5,3726,5569,12.4
5,10,Gelderland (PV),2149071,433.0,19481,9.0,21466,10.0,120167,55.8,105832,49.1,14335,12287,5.7
6,11,Utrecht (PV),1400057,943.0,14601,10.4,11551,8.2,84795,60.4,78737,56.1,6058,9087,6.5
7,12,Noord-Holland (PV),2976487,1118.0,28312,9.5,26284,8.8,210844,70.7,197166,66.1,13678,15529,5.2
8,13,Zuid-Holland (PV),3840460,1423.0,37271,9.7,34366,8.9,239313,62.1,219037,56.9,20276,22937,6.0
9,14,Zeeland (PV),391634,220.0,3334,8.5,4503,11.5,20568,52.4,18040,46.0,2528,1335,3.4
10,15,Noord-Brabant (PV),2644739,540.0,23904,9.0,26191,9.9,172663,65.0,151103,56.9,21560,19308,7.3
11,16,Limburg (PV),1133255,528.0,8655,7.6,13505,11.9,68046,60.0,61028,53.8,7018,2073,1.8

In [20]:
pop_stats.shape

(12, 15)

## Removing Unwanted Suffixes

In [21]:
pop_stats = pop_stats.replace({r' \(PV\)': ''}, regex=True)
pop_stats

,index,region,total_population,population_density,total_births,birth_ratio,total_deaths,death_ratio,total_arrivals,arrival_ratio,total_departures,departure_ratio,net_migration,total_population_growth,population_growth_ratio
0,5,Groningen,601347,260.0,4816,8.0,6294,10.5,58540,97.2,55699,92.5,2841,1486,2.5
1,6,Fryslân,661904,198.0,5684,8.6,7146,10.8,33334,50.3,29516,44.5,3818,2318,3.5
2,7,Drenthe,504129,191.0,4037,8.0,6045,12.0,26872,53.2,22388,44.3,4484,2400,4.8
3,8,Overijssel,1189033,359.0,11158,9.4,11781,9.9,56060,47.0,48614,40.8,7446,6756,5.7
4,9,Flevoland,450826,320.0,4890,10.8,3033,6.7,28001,61.7,24275,53.5,3726,5569,12.4
5,10,Gelderland,2149071,433.0,19481,9.0,21466,10.0,120167,55.8,105832,49.1,14335,12287,5.7
6,11,Utrecht,1400057,943.0,14601,10.4,11551,8.2,84795,60.4,78737,56.1,6058,9087,6.5
7,12,Noord-Holland,2976487,1118.0,28312,9.5,26284,8.8,210844,70.7,197166,66.1,13678,15529,5.2
8,13,Zuid-Holland,3840460,1423.0,37271,9.7,34366,8.9,239313,62.1,219037,56.9,20276,22937,6.0
9,14,Zeeland,391634,220.0,3334,8.5,4503,11.5,20568,52.4,18040,46.0,2528,1335,3.4
10,15,Noord-Brabant,2644739,540.0,23904,9.0,26191,9.9,172663,65.0,151103,56.9,21560,19308,7.3
11,16,Limburg,1133255,528.0,8655,7.6,13505,11.9,68046,60.0,61028,53.8,7018,2073,1.8

## Exporting Final Product

In [22]:
new_path = Path(f'{data_folder}/new_nederland_pop_stats.feather')
pop_stats.to_feather(new_path)

## Checking Column DTypes of the Exported Product

In [23]:
pd.read_feather(new_path).dtypes

index                        int64
region                      object
total_population             int64
population_density         float64
total_births                 int64
birth_ratio                float64
total_deaths                 int64
death_ratio                float64
total_arrivals               int64
arrival_ratio              float64
total_departures             int64
departure_ratio            float64
net_migration                int64
total_population_growth      int64
population_growth_ratio    float64
dtype: object